package com.oracletrial.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.List;

/**
 * Response returned by {@code /api/ask}.
 *
 * <p>Holds the LLM-generated answer plus the exact chunks it was built
 * from, so a caller can verify the answer against real document citations
 * instead of trusting it blindly. Sources always come from actual
 * retrieved chunks - they are never invented.</p>
 */
@Getter
@AllArgsConstructor
public class AskResponse {

    /** Answer generated by the LLM, grounded only in the retrieved chunks. */
    private final String answer;

    /** Documents/pages/chunks the answer was actually built from. */
    private final List<Source> sources;

    /**
     * One citation: identifies exactly where a piece of the answer came from.
     */
    @Getter
    @AllArgsConstructor
    public static class Source {

        /** Name of the source document, e.g. "hr-policy.pdf". */
        private final String document;

        /** Page number the chunk came from, or {@code null} if unknown. */
        private final Integer page;

        /** Chunk number within the document, starting at 1. */
        private final int chunk;
    }
}
